import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactQueryClientProvider } from '@/app/react-query-client-provider';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'UseSuspenseQuery',
  description: 'Generated by entrolEC',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >

    <ReactQueryClientProvider>
      <div className="flex flex-col p-4 gap-4">
        <Link href="/" className="bg-amber-300 hover:opcity-60 rounded-lg font-medium p-2 text-center">메인으로 이동</Link>
        {children}
      </div>
    </ReactQueryClientProvider>
    </body>
    </html>
  );
}
